### ISSUE TITLE
Assymetric margins

### ISSUE THREAD

**Issue by kswannet** [skilkis/tudelft-light#25]
Option to reduce margins on the outside of pages (non-binding side) instead of symmetric margins on inside and outside of the page. This would allow slightly more space for text and wide tables/images and reducing page count.

**Comment by skilkis** [comment]
@kswannet this can be done easily by passing the `twoside` option to the at the start of your `main.tex` file along with an updated call to the `geometry` package as shown below. In the future the two-side option can automatically update the options passed to the `geometry` package.

```tex
\PassOptionsToPackage{bindingoffset=2pc}{geometry}
\documentclass[11pt,a4paper,reqno,fancyheader,twoside]{tudelft-light/report}
```
