### ISSUE TITLE
Add command/macro for research questions

### ISSUE THREAD

**Issue by kswannet** [skilkis/tudelft-light#27]
something as discussed here:
https://tex.stackexchange.com/questions/525921/ideas-for-presenting-the-research-question

something like this:
```tex
\newlist{questions}{enumerate}{2}
\setlist[questions,1]{label=\bf{RQ-\arabic*.},ref=RQ-\arabic*, leftmargin=*}
\setlist[questions,2]{label*=\indent \bf{\arabic*.},ref=\thequestionsi.\arabic*}
\let\origitem\item
\renewcommand{\item}{\normalfont\origitem}
\newcommand{\question}{\normalfont\origitem\em}
\crefname{questionsi}{research question}{research questions}
\crefname{questionsii}{research sub-question}{research sub-questions}
```

**Comment by skilkis** [comment]
@kswannet this is really cool! Perhaps we can generalize it as a way to add references to arbitrary listed items. Personally I feel the need for implementing something like this also for requirement lists. So if we can make a macro to allow a user to input the prefix of the list, that would be great!
