### ISSUE TITLE
Remove si from nomenclature or add optional argument to allow listing constants

### ISSUE THREAD

**Issue by kswannet** [skilkis/tudelft-light#31]
Right now the nomenclature only allows units.
It would be nice to be able to also input values for listing constants, but right now this is not possible.
Alternatively, a separate nomenclature commance for constants which takes 2 arguments: value and unit.
![image](https://user-images.githubusercontent.com/39293496/101664452-26ee2980-3a4c-11eb-9aa1-ad98d063371d.png)

**Comment by skilkis** [comment]
@kswannet I have just added an optional argument to the \nomunit macro in [9628f4e] that you can use as follows:

```tex
\nomenclature[C]{F}{Avogadro's Number \nomunit[96.485332][\per\mol]}
```

This will be included in the next release. For now update the submodule using the following:

```bash
git submodule update --remote
```

[9628f4e]: https://github.com/skilkis/tudelft-light-template/commit/9628f4e4144e2408de1c96f96770623768550b28
